stages:
  - build
  - publish
  - dockerize

variables:
  MAVEN_CLI_OPTS: "-s settings.xml -B"

default:
  image: maven:3.8.5-openjdk-17

cache:
  key: shared-m2-repo
  paths:
    - /root/.m2/repository
  policy: pull-push

build:
  stage: build
  script:
    - echo "Building and Testing project..."
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/*.jar


publish_artifacts:
  stage: publish
  script:
    - echo "Publishing artifacts..."
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  dependencies:
    - build

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin registry.hub.docker.com
  script:
    - echo "Building Docker image..."
    - docker build -t whastappbroski:latest .
    - echo "Pushing image to DockerHub"
    - docker push "$DOCKERHUB_USERNAME/whatsappbroski:latest"
  dependencies:
    - build

  