stages:
  - setup
  - build
  - test
  - publish

variables:
  MAVEN_CLI_OPTS: "-s settings.xml -B"

cache:
  paths:
    - .m2.repository

setup:
  image: openjdk:17
  stage: setup
  script:
    - echo "Installing Maven..."
    - apt-get update && apt-get install -y maven
    - mvn --version
  artifacts:
    paths:
      - /usr/share/maven
    expire_in: 1 week

build:
  image: openjdk:17
  stage: build
  script:
    - echo "Building Project..."
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar

test:
  image: openjdk:17
  stage: test
  script:
    - echo "Running tests..."
    - mvn $MAVEN_CLI_OPTS

publish_artifacts:
  image: openjdk:17
  stage: publish
  script:
    - echo "Publishing artifacts..."
    - mvn $MAVEN_CLI_OPTS deploy
  dependencies:
    - test