stages:
  - build
  - publish

variables:
  MAVEN_CLI_OPTS: "-s settings.xml -B"

default:
  image: maven:3.8.5-openjdk-17

cache:
  key: shared-m2-repo
  paths:
    - .m2/repository
  policy: pull-push

build:
  stage: build
  script:
    - echo "Building and Testing project..."
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/*.jar


publish_artifacts:
  stage: publish
  script:
    - echo "Publishing artifacts..."
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  dependencies:
    - build