stages:
  - build
  - test
  - publish

variables:
  MAVEN_CLI_OPTS: "-s settings.xml -B -DskipTests"

cache:
  paths:
    - .m2/repository

build:
  image: openjdk:17
  stage: build
  script:
    - echo "Building Project..."
    - ./mvnw $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar

test:
  image: openjdk:17
  stage: test
  script:
    - echo "Running tests..."
    - ./mvnw test
  dependencies:
    - build

publish_artifacts:
  image: openjdk:17
  stage: publish
  script:
    - echo "Publishing artifacts..."
    - ./mvnw $MAVEN_CLI_OPTS deploy
  dependencies:
    - test