stages:
  - build
  - publish
  - dockerize

variables:
  MAVEN_CLI_OPTS: "-s settings.xml -B"

default:
  image: maven:3.8.5-openjdk-17

cache:
  key: shared-m2-repo
  paths:
    - /root/.m2/repository
  policy: pull-push

build:
  stage: build
  script:
    - echo "Building and Testing project..."
    - mvn $MAVEN_CLI_OPTS clean install
  artifacts:
    paths:
      - target/*.jar


publish_artifacts:
  stage: publish
  script:
    - echo "Publishing artifacts..."
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  dependencies:
    - build

dockerize:
  stage: dockerize
  image: docker:latest
  services:
    - docker:latest-dind
  script:
    - echo "Building Docker Image..."
    - docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest .
    - echo "Pushing to DockerHub..."
    - echo $DOCKERHUB_TOKEN | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:latest
  dependencies:
    - publish_artifacts
  